### ISSUE TITLE
Adding expertise doesn't account for pre-existing data

### ISSUE THREAD

**Issue by mercuryhg31** [Instantutor/Instantutor#89]
Editing expertise simply tacks on a whole new unit for both the field of study and courses, even if they're repeats.

**To replicate:**
1. Fill out expertise form with some information.
2. Submit query and see addition to profile.
3. Add expertise with same field of study and courses.
4. Submit query and see issue.

**Expected:** This should keep all new courses within the same major field of study under the same heading (all of the above should be under "Computer Science") and not show the same courses multiple times.

![image](https://user-images.githubusercontent.com/26150304/174351376-b9707275-57cd-42b0-9155-3a7c2d0eba6b.png)
![image](https://user-images.githubusercontent.com/26150304/174351395-7c7284b1-2324-411d-85ef-91e626c1e9d2.png)

**Comment by Samyuth** [comment]
Essentially we ultimately want a way to edit the expertise, this will ultimately come from merging the expertise with the profile
